In [3]:
from sklearn.datasets import make_classification
import torch
import torch.nn as nn

In [7]:
#step 1:create a synthetc classification dataset using sklearn
X, y = make_classification(
    n_samples=10, # Reduced number of samples for simplicity
    n_features=2, # Reduced number of features for simplicity
    n_informative=2, # All features are informative
    n_redundant=0,# Reduced number of redundant features for simplicity
    n_classes=2, # Binary classification
    random_state=42) #reproducibility

In [17]:
# Step 2: Convert to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [18]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [19]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [20]:
from torch.utils.data import Dataset, DataLoader # load the Dataset and DataLoader classes from utils.data

In [21]:
class CustomDataset(Dataset):

    def __init__(self, features, labels):
        self.features =features
        self.labels = labels

    def __len__(self):
        self.features.shape[0] # return the number of samples
        
    def __getitem__(self, index):
        return self.features[index], self.labels[index] # return the feature and label at the given index

In [22]:
dataset = CustomDataset(X,y)

In [26]:
dataset[3]

(tensor([-0.7206, -0.9606]), tensor(0))

In [28]:
from torch.utils.data import TensorDataset, DataLoader

dataset = TensorDataset(X, y)

# Correct way
loader = DataLoader(dataset, batch_size=2, shuffle=True)

# Example: iterate through batches
for batch_X, batch_y in loader:
    print(batch_X, batch_y)


tensor([[-0.5872, -1.9717],
        [ 1.0683, -0.9701]]) tensor([0, 1])
tensor([[-0.9382, -0.5430],
        [-0.7206, -0.9606]]) tensor([1, 0])
tensor([[ 1.7774,  1.5116],
        [-1.9629, -0.9923]]) tensor([1, 0])
tensor([[ 1.7273, -1.1858],
        [-1.1402, -0.8388]]) tensor([1, 0])
tensor([[-2.8954,  1.9769],
        [ 1.8997,  0.8344]]) tensor([0, 1])


In [29]:
DataLoader = DataLoader(dataset, batch_size=2, shuffle=True) # create a DataLoader with a batch size of 2 and shuffling enabled

In [30]:
for batch_features, batch_labels in DataLoader:
    print(batch_features)  # Print the features and labels in each batch
    print(batch_labels)
    print("-"*50)  # Separator for clarity

tensor([[-0.9382, -0.5430],
        [ 1.8997,  0.8344]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-2.8954,  1.9769]])
tensor([1, 0])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.7273, -1.1858]])
tensor([0, 1])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------
