In [1]:
import torch
print(torch.__version__)

2.8.0+cpu


In [4]:
# pip install torch torchvision torchaudio torchtext textual

In [8]:
if torch.cuda.is_available():
    print("CUDA is available")
    print(f"using GPU :{torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


In [10]:
#creating a tensor

# using empty

In [13]:
# using empty -> creates a tensor without initializing its values
# it is faster than torch.zeros or torch.ones
# but the values in the tensor will be uninitialized and may contain garbage values
x = torch.empty(2, 3)
print(x)

tensor([[9.9383e-32, 9.8792e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [14]:
type(x)

torch.Tensor

In [16]:
#using zeros  -> creates a tensor filled with zeros
x = torch.zeros(2, 3)
print(x)    

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [18]:
#using randn -> creates a tensor filled with random numbers from a normal distribution , each time changing
x = torch.randn(2, 3)
print(x)    

tensor([[-0.1334,  0.3102,  0.4824],
        [ 1.5139, -0.4559, -0.3496]])


In [19]:
#manually seed  -> sets the seed for random number generation ,
# this ensures that the random numbers generated are the same each time you run the code
torch.manual_seed(42)
x = torch.randn(2, 3)
print(x)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])


In [20]:
x

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])

In [21]:
# using tensor -> creates a tensor from a list
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [22]:
#other ways to create tensors
x = torch.arange(0, 10, 2)

In [23]:
x

tensor([0, 2, 4, 6, 8])

In [24]:
#linspace -> creates a tensor with evenly spaced values between start and end
x = torch.linspace(0, 1, steps=5)
print(x)    

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [25]:
# ussing eye -> creates a 2D tensor with ones on the diagonal and zeros elsewhere
x = torch.eye(3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [26]:
#using full -> creates a tensor filled with a specified value
x = torch.full((2, 3), 7)
print(x)

tensor([[7, 7, 7],
        [7, 7, 7]])


In [27]:
#Tensor shape

In [28]:
x= torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.shape)  # Output: torch.Size([2, 3])

torch.Size([2, 3])


In [30]:
# create the same tensor with the same shape but uninitialized values
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [32]:
torch.zeros_like(x)  # creates a tensor of zeros with the same shape as x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [33]:
torch.ones_like(x)   # creates a tensor of ones with the same shape as x

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
#tensor datatypes
x = torch.tensor([1, 2, 3], dtype=torch.float32)

In [35]:
x.dtype  # Output: torch.float32

torch.float32

In [37]:
#using to() -> converts the tensor to a different datatype
x = x.to(torch.int32)
print(x.dtype)  # Output: torch.int32
x

torch.int32


tensor([1, 2, 3], dtype=torch.int32)

In [39]:
torch.randn_like(x,dtype=torch.float32)  # creates a tensor with the same shape as x but with random values

tensor([ 2.2082, -0.6380,  0.4617])

In [43]:
#mathematical operations
y = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
y

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [42]:
# 1. scalar addition
z = y + 2
z

tensor([[3., 4., 5.],
        [6., 7., 8.]])

In [45]:
x=torch.randn(2, 3)
x

tensor([[ 0.9580,  1.3221,  0.8172],
        [-0.7658, -0.7506,  1.3525]])

In [46]:
#addition
x +2
#subtraction
x - 2   
#multiplication
x * 2   
#division
x / 2       
#division
x / 2.0 
#integer division
(x  * 100)// 2 
#modulus
x % 2   
#power
x ** 2

tensor([[0.9177, 1.7480, 0.6678],
        [0.5865, 0.5634, 1.8294]])

In [47]:
#copy a tensor
a =torch.rand(2,3)

In [48]:
a

tensor([[0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952]])

In [49]:
b=a

In [50]:
a[0, 0] = 100  # modifying a will also modify b
b  # Output: tensor([[100.0000, 0.0000, 0.0000], [0.0000, 0.0000, 0.0000]])

tensor([[100.0000,   0.2814,   0.7886],
        [  0.5895,   0.7539,   0.1952]])

In [51]:
a

tensor([[100.0000,   0.2814,   0.7886],
        [  0.5895,   0.7539,   0.1952]])

In [52]:
id(a), id(b)  # both a and b point to the same memory location

(2778413791760, 2778413791760)

In [53]:
b = a.clone()  # creates a copy of the tensor
b

tensor([[100.0000,   0.2814,   0.7886],
        [  0.5895,   0.7539,   0.1952]])

In [54]:
a[0, 0] = 10  # modifying a will also modify b

In [59]:
a

tensor([[10.0000,  0.2814,  0.7886],
        [ 0.5895,  0.7539,  0.1952]])

In [60]:
b

tensor([[100.0000,   0.2814,   0.7886],
        [  0.5895,   0.7539,   0.1952]])

In [61]:
id(a), id(b) 

(2778413791760, 2778424342960)

In [62]:
#tensor operations on GPU

In [63]:
torch.cuda.is_available()  # check if CUDA is available

False

In [64]:
device = torch.device("cuda")

In [65]:
device

device(type='cuda')

In [67]:
#creating a tensor on GPU
x = torch.randn((2, 3), device=device)
x

AssertionError: Torch not compiled with CUDA enabled

In [68]:
import torch
print(torch.__version__)
print("CUDA available:", torch.cuda.is_available())


2.8.0+cpu
CUDA available: False


In [71]:
#Reshape Tensor
x = torch.ones(4,4)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [72]:
x.reshape(2, 8)  # Reshape to 2 rows and 8 columns

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [74]:
x.flatten()  # Flatten the tensor to a 1D tensor

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [75]:
b=torch.randn((2,3,4))

In [77]:
b

tensor([[[ 1.3852, -0.4459,  1.4451,  0.8564],
         [ 2.2181,  0.5232,  0.3466, -0.1973],
         [ 1.1412,  0.0516,  0.7281, -0.7106]],

        [[-0.6021,  0.9604,  0.4048, -1.3543],
         [ 1.3347,  0.4835, -0.1976,  1.2683],
         [ 1.2243,  0.0981,  1.7423, -1.3527]]])

In [78]:
b.permute(2, 0, 1)  # Change the order of dimensions

tensor([[[ 1.3852,  2.2181,  1.1412],
         [-0.6021,  1.3347,  1.2243]],

        [[-0.4459,  0.5232,  0.0516],
         [ 0.9604,  0.4835,  0.0981]],

        [[ 1.4451,  0.3466,  0.7281],
         [ 0.4048, -0.1976,  1.7423]],

        [[ 0.8564, -0.1973, -0.7106],
         [-1.3543,  1.2683, -1.3527]]])

In [79]:
b.permute(2, 1, 0).shape

torch.Size([4, 3, 2])

In [80]:
#Numpy and pytorch tensors
import numpy as np

In [81]:
a = torch.tensor([1, 2, 3])

In [83]:
a

tensor([1, 2, 3])

In [84]:
b=a.numpy()  # Convert PyTorch tensor to NumPy array

In [85]:
b

array([1, 2, 3])